application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      xwalk-omnichannel:
        license: Apache-2.0
        actions:
          json2html:
            function: actions/json2html/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
